version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./twitter-clone-drf:/twitter-clone
    command: sh -c "python manage.py runserver 0.0.0.0:8000 --settings=config.settings.development"
    environment:
      - DEBUG=1