version: '3.7'

services:
  app:
    container_name: twitter-clone
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_SETTINGS_MODULE=config.settings.development
    depends_on:
      - database
  nginx-proxy:
    container_name: proxy
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "8000:8080"
    depends_on:
      - app
  database:
    container_name: postgres
    image: "postgres:13"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5400:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  static_data: