# Generated by Django 3.1.7 on 2021-04-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20210414_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='comment_tweet',
            new_name='comment',
        ),
    ]
