# Generated by Django 3.1.7 on 2021-04-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20210413_2347'),
        ('tweets', '0003_auto_20210414_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='comment_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweets', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='tweets.tweet'),
        ),
    ]
