# Generated by Django 3.1.7 on 2021-04-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.Field(blank=True, null=True),
        ),
    ]
