# Generated by Django 3.1.7 on 2021-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
