# Generated by Django 3.1.7 on 2021-04-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210414_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=models.FileField(blank=True, null=True, upload_to='user/cover/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='user/profile/'),
        ),
    ]
