# Generated by Django 3.1.7 on 2021-04-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20210414_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cover_photo',
            new_name='cover_picture',
        ),
    ]
