name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: twitter
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Lint with flake8
        working-directory: ./twitter-clone-drf
        run: |
          pip install flake8
          flake8
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Django Testing
        working-directory: ./twitter-clone-drf
        run: |
          pip install -r requirements.txt
          python3 manage.py test --settings=config.settings.development
      - name: Code coverage
        working-directory: ./twitter-clone-drf
        run: |
          pip install coverage
          coverage run manage.py test --settings=config.settings.development
          coverage report
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Django
        id: docker_build_django
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/twitter-clone:latest

      # - name: Upgrade images on Droplet
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       cd ${{ secrets.DIRECTORY }}
      #       docker-compose down
      #       docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/twitter-clone
      #       docker-compose up --build -d