name: Django Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Lint with flake8
        working-directory: ./twitter-clone-drf
        run: |
          pip install flake8
          flake8
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Django Testing
        working-directory: ./twitter-clone-drf
        run: |
          python3 manage.py test


